/*
 * SetupWizard.java
 * 
 * Copyright (c) 2011 Matthew Doll <mdoll at homenet.me>.
 * 
 * This file is part of HomeNet.
 * 
 * HomeNet is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * HomeNet is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with HomeNet.  If not, see <http ://www.gnu.org/licenses/>.
 */

/*
 * SetupWizard.java
 *
 * Created on May 27, 2011, 1:02:45 AM
 */
package homenetapp;

import java.awt.datatransfer.*;


/**
 *
 * @author Matthew Doll <mdoll at homenet.me>
 */
public class oldSetupWizardGui extends javax.swing.JFrame {

    HomeNetApp homenetapp;
    
    /** Creates new form SetupWizard */
    public oldSetupWizardGui(HomeNetApp homenetapp) {
        this.homenetapp = homenetapp;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Step0 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Step1 = new javax.swing.JPanel();
        serverLabel1 = new javax.swing.JLabel();
        apiKeyLabel1 = new javax.swing.JLabel();
        serverTextField = new javax.swing.JTextField();
        apiKeyTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Step2 = new javax.swing.JPanel();
        clientPortTextField = new java.awt.TextField();
        clientPortLabel = new javax.swing.JLabel();
        allowIncomingPackets = new javax.swing.JCheckBox();
        clientUPnPCheckBox = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        nextButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        backButton.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomeNet App Setup Wizard");

        jPanel1.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel2.setText("Welcome to the HomeNet App");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setText("This wizard will help you setup and configure your HomeNet");

        jLabel4.setText("If you haven't done so already you need to setup an account at HomeNet.me");

        javax.swing.GroupLayout Step0Layout = new javax.swing.GroupLayout(Step0);
        Step0.setLayout(Step0Layout);
        Step0Layout.setHorizontalGroup(
            Step0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step0Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Step0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        Step0Layout.setVerticalGroup(
            Step0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step0Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jPanel1.add(Step0, "card0");

        Step1.setBorder(javax.swing.BorderFactory.createTitledBorder("Server Settings"));

        serverLabel1.setText("Server:");

        apiKeyLabel1.setText("API Key:");

        serverTextField.setEditable(false);
        serverTextField.setText("homenet.me");

        jButton1.setText("Paste");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Step1Layout = new javax.swing.GroupLayout(Step1);
        Step1.setLayout(Step1Layout);
        Step1Layout.setHorizontalGroup(
            Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(apiKeyLabel1)
                    .addComponent(serverLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serverTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Step1Layout.createSequentialGroup()
                        .addComponent(apiKeyTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        Step1Layout.setVerticalGroup(
            Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serverLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apiKeyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apiKeyLabel1)
                    .addComponent(jButton1))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        jPanel1.add(Step1, "card1");

        Step2.setBorder(javax.swing.BorderFactory.createTitledBorder("Client Settings"));
        Step2.setVisible(false);

        clientPortTextField.setEditable(false);
        clientPortTextField.setText("2443");
        clientPortTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientPortTextFieldActionPerformed(evt);
            }
        });

        clientPortLabel.setText("Port:");

        allowIncomingPackets.setSelected(true);
        allowIncomingPackets.setText("Enable Incoming Packets");
        allowIncomingPackets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allowIncomingPacketsActionPerformed(evt);
            }
        });

        clientUPnPCheckBox.setText("Enable UPnP Port Forwarding");

        javax.swing.GroupLayout Step2Layout = new javax.swing.GroupLayout(Step2);
        Step2.setLayout(Step2Layout);
        Step2Layout.setHorizontalGroup(
            Step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allowIncomingPackets)
                    .addGroup(Step2Layout.createSequentialGroup()
                        .addComponent(clientPortLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(clientUPnPCheckBox))
                .addContainerGap())
        );
        Step2Layout.setVerticalGroup(
            Step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step2Layout.createSequentialGroup()
                .addComponent(allowIncomingPackets)
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(clientPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientPortLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientUPnPCheckBox)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jPanel1.add(Step2, "card2");

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButton)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {backButton, nextButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton)
                    .addComponent(backButton))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int currentPage = 0;
    
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if(currentPage == 0)
        {
            ((java.awt.CardLayout)jPanel1.getLayout()).next(jPanel1);
            backButton.setVisible(true);
            currentPage++;
        } else if(currentPage == 1) {
            ((java.awt.CardLayout)jPanel1.getLayout()).next(jPanel1);
            nextButton.setText("Done");
            currentPage++;
        } else if(currentPage == 2){
            //process done
            save();
            java.awt.event.WindowEvent wev = new java.awt.event.WindowEvent(this, java.awt.event.WindowEvent.WINDOW_CLOSING);
            java.awt.Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(wev);

            this.dispose();
            //this.dispose();
            currentPage++;
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void clientPortTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientPortTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientPortTextFieldActionPerformed

    private void allowIncomingPacketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allowIncomingPacketsActionPerformed
       javax.swing.JCheckBox checkbox = (javax.swing.JCheckBox)evt.getSource();
        if(checkbox.isSelected()){
            clientUPnPCheckBox.setEnabled(true);
            clientPortLabel.setEnabled(true);
            clientPortTextField.setEnabled(true);
            System.out.println("Selected");
        } else {
            clientUPnPCheckBox.setEnabled(false);
            clientPortLabel.setEnabled(false);
            clientPortTextField.setEnabled(false);
            System.out.println("Not Selected");
        }
    }//GEN-LAST:event_allowIncomingPacketsActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        if(currentPage <= 2){
            ((java.awt.CardLayout)jPanel1.getLayout()).previous(jPanel1);
            currentPage--;
            backButton.setVisible(false);
            nextButton.setText("Next");
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          String data = "";
         try {
            Clipboard clipboard = java.awt.Toolkit.getDefaultToolkit().getSystemClipboard();


            Transferable content = clipboard.getContents(null);
            if (content != null){
            data = (String)content.getTransferData(DataFlavor.stringFlavor);
            }  
         } catch (Exception e) {
                System.err.println("Error getting String from clipboard: " + e);
            }

           apiKeyTextField.setText(data);
        //    homenetApikey = data;
        //    startHomeNetUplink();
        //    print("testing new api key");

        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void save(){
        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Step0;
    private javax.swing.JPanel Step1;
    private javax.swing.JPanel Step2;
    private javax.swing.JCheckBox allowIncomingPackets;
    private javax.swing.JLabel apiKeyLabel1;
    private javax.swing.JTextField apiKeyTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel clientPortLabel;
    private java.awt.TextField clientPortTextField;
    private javax.swing.JCheckBox clientUPnPCheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel serverLabel1;
    private javax.swing.JTextField serverTextField;
    // End of variables declaration//GEN-END:variables
}
